#!/bin/bash

IFS=
function wait_response {
    echo "Do you wish to continue?"
    read -s -n 1 key  
    if [[ $key = "" ]]; then 
       echo "Continue";
    elif [[  $key = "c" ]]; then
       echo "Exit";
       exit;
    fi
}

function enter_parameter {
  echo $1;
  read param;
  echo "Param $param";
  eval "$2='$param'";
  return $param;
}

function changeDir {
    cd $1;
}

changeDir '/vz/template/cache';
#cd /vz/template/cache
wait_response;
echo 'wget -P /vz/template/cache http://download.openvz.org/template/precreated/ubuntu-14.04-x86_64-minimal.tar.gz';
wget -P /vz/template/cache http://download.openvz.org/template/precreated/ubuntu-14.04-x86_64-minimal.tar.gz
wait_response;
echo 'yum -y install ploop';
yum -y install ploop
#wait_response;

enter_parameter "Enter number of virtual machine::" vz_num;
echo "vzctl create $vz_num --ostemplate ubuntu-14.04-x86_64-minimal --config basic";
vzctl create $vz_num --ostemplate ubuntu-14.04-x86_64-minimal --config basic
wait_response;
echo "vzctl set $vz_num --onboot yes --save";
vzctl set $vz_num --onboot yes --save
#wait_response;
enter_parameter "Enter name of virtual machine::" vz_name;
echo "vzctl set $vz_num --hostname $vz_name --save";
vzctl set $vz_num --hostname $vz_name --save;
#wait_response;
enter_parameter "Enter ip of virtual machine::" vz_ip;
echo "vzctl set $vz_num --ipadd $vz_ip --save";
vzctl set $vz_num --ipadd $vz_ip --save


enter_parameter "Enter disk of virtual machine::" vz_disk;
echo "vzctl set $vz_num --diskspace $vz_disk --save";
vzctl set $vz_num --diskspace $vz_disk --save;

wait_response;
echo "vzctl set $vz_num --numothersock 120 --save";
vzctl set $vz_num --numothersock 120 --save
wait_response;
echo "vzctl set $vz_num --nameserver 8.8.8.8 --nameserver 8.8.4.4 --nameserver 145.253.2.75 --save";
vzctl set $vz_num --nameserver 8.8.8.8 --nameserver 8.8.4.4 --nameserver 145.253.2.75 --save
wait_response;
echo "vzctl start $vz_num";
vzctl start $vz_num
wait_response;
echo "vzctl exec $vz_num passwd";
vzctl exec $vz_num passwd
wait_response;

